import type { SettingsPanelState } from "../types";

export type ExportPayload = { fileName: string; mimeType: "text/plain;charset=utf-8"; content: string };

export function buildExportPayload(state: SettingsPanelState, fileName = "settings-panel"): ExportPayload {
  return {
    fileName: `${fileName || "settings-panel"}.jsx`,
    mimeType: "text/plain;charset=utf-8",
    content: buildReactCode(state),
  };
}

export function buildReactCode(state: SettingsPanelState) {
  return [
    "import * as React from \"react\";",
    "",
    "const state = " + JSON.stringify(state, null, 2) + ";",
  "",
  "function resolveFont(s) { return s.fontBucket === \"google\" ? '\"' + s.googleFontFamily + \"\ , sans-serif' : \"inherit\"; }",
  "function buildShadow(s) { if (!s.shadowEnabled) return \"none\"; var hex = Math.round(s.shadowOpacity * 255).toString(16).padStart(2, \"0\"); return s.shadowX + \"px \" + s.shadowY + \"px \" + s.shadowBlur + \"px \" + s.shadowSpread + \"px \" + s.shadowColor + hex; }",
    "",
    "const SETTING_GROUPS = [",
    "  { title: \"Account\", description: \"Profile and identity settings\", fields: [\"Display name\", \"Workspace slug\", \"Contact email\"] },",
    "  { title: \"Notifications\", description: \"Delivery and alert preferences\", fields: [\"Product updates\", \"Security alerts\", \"Weekly digest\"] },",
    "  { title: \"Privacy\", description: \"Visibility and data controls\", fields: [\"Public profile\", \"Usage analytics\", \"Data retention\"] },",
    "  { title: \"Billing\", description: \"Invoices and payment settings\", fields: [\"Plan\", \"Invoice email\", \"Spend alerts\"] },",
    "  { title: \"Integrations\", description: \"Connected app permissions\", fields: [\"API access\", \"Webhook endpoint\", \"Sync cadence\"] },",
    "  { title: \"Advanced\", description: \"Administrative defaults\", fields: [\"Default role\", \"Session timeout\", \"Beta access\"] },",
    "];",
    "",
    "function clamp(value, min, max) {",
    "  return Math.max(min, Math.min(max, value));",
    "}",
    "",
    "function resolveStatus() {",
    "  if (state.previewState === \"error\" || state.saveState === \"error\") return { role: \"alert\", text: \"Unable to save settings. Review the highlighted fields and try again.\", color: \"#fca5a5\" };",
    "  if (state.previewState === \"success\" || state.saveState === \"success\") return { role: \"status\", text: \"Settings saved successfully.\", color: \"#86efac\" };",
    "  if (state.previewState === \"loading\" || state.saveState === \"saving\") return { role: \"status\", text: \"Saving settings...\", color: state.accent };",
    "  if (state.dirtyState) return { role: \"status\", text: \"Unsaved changes are ready to save.\", color: state.accent };",
    "  return { role: \"status\", text: \"Settings are up to date.\", color: state.muted };",
    "}",
    "",
    "export default function SettingsPanelComponent() {",
    "  const groupCount = clamp(Number(state.groupCount) || 3, 1, SETTING_GROUPS.length);",
    "  const controlCount = clamp(Number(state.controlCount) || 8, 1, 16);",
    "  const groups = SETTING_GROUPS.slice(0, groupCount);",
    "  const status = resolveStatus();",
    "  const describedBy = `${state.id}-description ${state.id}-status`;",
    "  const shellStyle = {",
    "    width: state.width,",
    "    minHeight: state.height,",
    "    display: \"grid\",",
    "    gap: state.gap,",
    "    padding: state.padding,",
    "    borderRadius: state.radius,",
    "    border: `${state.borderWidth}px ${state.borderStyle} ${state.disabled && state.disabledUseCustomColors ? state.disabledBorder : state.border}`,",
    "    boxShadow: `0 ${Math.round(state.shadow / 3)}px ${state.shadow}px rgba(15, 23, 42, 0.26)`,",
    "    background: state.background,",
    "    color: state.foreground,",
    "    fontFamily: resolveFont(state),",
    "    cursor: state.disabled ? state.disabledCursor : undefined,",
    "    opacity: state.disabled ? 0.58 : 1,",
    "  };",
    "  const groupStyle = { display: \"grid\", gap: 12, margin: 0, padding: 14, border: `1px solid ${state.border}`, borderRadius: Math.max(12, state.radius - 8), transition: state.motion ? \"opacity 0.2s ease, border-color 0.2s ease\" : \"none\" };",
    "  const labelStyle = { display: \"grid\", gap: 6, color: state.foreground, fontSize: state.bodySize };",
    "  const controlStyle = { width: \"100%\", border: `1px solid ${state.border}`, borderRadius: 12, padding: \"10px 12px\", background: \"transparent\", color: state.foreground };",
    "",
    "  return (",
    "    <form id={state.id} role={state.role} aria-label={state.ariaLabel} aria-describedby={describedBy} onSubmit={(event) => event.preventDefault()} style={shellStyle}>",
    "      <header style={{ display: \"grid\", gap: 6 }}>",
    "        <h2 style={{ margin: 0, fontSize: state.titleSize, fontWeight: state.fontWeight }}>{state.title}</h2>",
    "        <p id={`${state.id}-description`} style={{ margin: 0, color: state.muted, fontSize: state.bodySize }}>{state.description}</p>",
    "      </header>",
    "",
    "      {groups.map((group, groupIndex) => (",
    "        <fieldset key={group.title} style={groupStyle}>",
    "          <legend>{group.title}</legend>",
    "          <p id={`${state.id}-group-${groupIndex}-description`} style={{ margin: 0, color: state.muted, fontSize: 12 }}>{group.description}</p>",
    "          {group.fields.slice(0, Math.max(1, Math.ceil(controlCount / groupCount))).map((field, fieldIndex) => {",
    "            const fieldId = `${state.id}-${groupIndex}-${fieldIndex}`;",
    "            const helpId = `${fieldId}-help`;",
    "            const kind = (groupIndex + fieldIndex) % 3;",
    "            if (kind === 0) {",
    "              return (",
    "                <label key={field} htmlFor={fieldId} style={labelStyle}>",
    "                  {field}",
    "                  <input id={fieldId} name={field.toLowerCase().replaceAll(\" \", \"-\")} type=\"text\" defaultValue={fieldIndex === 0 ? state.label : \"\"} aria-describedby={helpId} aria-invalid={state.previewState === \"error\" ? \"true\" : undefined} disabled={state.disabled} style={controlStyle} />",
    "                  <span id={helpId} style={{ color: state.muted, fontSize: 12 }}>Update {field.toLowerCase()} for this settings group.</span>",
    "                </label>",
    "              );",
    "            }",
    "            if (kind === 1) {",
    "              return (",
    "                <label key={field} htmlFor={fieldId} style={labelStyle}>",
    "                  {field}",
    "                  <select id={fieldId} name={field.toLowerCase().replaceAll(\" \", \"-\")} defaultValue=\"balanced\" aria-describedby={helpId} disabled={state.disabled} style={controlStyle}>",
    "                    <option value=\"minimal\">Minimal</option>",
    "                    <option value=\"balanced\">Balanced</option>",
    "                    <option value=\"strict\">Strict</option>",
    "                  </select>",
    "                  <span id={helpId} style={{ color: state.muted, fontSize: 12 }}>Choose how strongly this setting should apply.</span>",
    "                </label>",
    "              );",
    "            }",
    "            return (",
    "              <label key={field} htmlFor={fieldId} style={{ display: \"flex\", alignItems: \"center\", justifyContent: \"space-between\", gap: 12, fontSize: state.bodySize, transition: state.motion ? \"background 0.15s ease, color 0.15s ease\" : \"none\" }}>",
    "                <span>",
    "                  <strong>{field}</strong>",
    "                  <small id={helpId} style={{ display: \"block\", color: state.muted }}>Toggle {field.toLowerCase()} for this workspace.</small>",
    "                </span>",
    "                <input id={fieldId} name={field.toLowerCase().replaceAll(\" \", \"-\")} type=\"checkbox\" defaultChecked={state.dirtyState} aria-describedby={helpId} disabled={state.disabled} />",
    "              </label>",
    "            );",
    "          })}",
    "        </fieldset>",
    "      ))}",
    "",
    "      <p id={`${state.id}-status`} role={status.role} aria-live=\"polite\" style={{ margin: 0, color: status.color, fontSize: 13 }}>{status.text}</p>",
    "",
    "      <div style={{ display: \"flex\", flexWrap: \"wrap\", gap: 10 }}>",
    "        <button type=\"submit\" disabled={state.disabled || state.previewState === \"loading\"} style={{ border: 0, borderRadius: 12, padding: \"10px 14px\", background: state.accent, color: state.actionText, fontWeight: 700, transition: state.motion ? \"background 0.15s ease, opacity 0.15s ease\" : \"none\" }}>Save settings</button>",
    "        {state.showReset && <button type=\"reset\" disabled={state.disabled} style={{ border: `1px solid ${state.border}`, borderRadius: 12, padding: \"10px 14px\", background: \"transparent\", color: state.foreground, transition: state.motion ? \"border-color 0.15s ease, color 0.15s ease\" : \"none\" }}>Reset settings</button>}",
    "      </div>",
    "    </form>",
    "  );",
    "}",
    "",
  ].join("\n");
}
